version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      tanstack-router:
        patterns:
          - "@tanstack/react-router"
          - "@tanstack/router-plugin"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
