/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThoughtsIndexRouteImport } from './routes/thoughts/index'
import { Route as ThoughtsReLevelingAnEngineeringOrgRouteImport } from './routes/thoughts/re-leveling-an-engineering-org'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThoughtsIndexRoute = ThoughtsIndexRouteImport.update({
  id: '/thoughts/',
  path: '/thoughts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThoughtsReLevelingAnEngineeringOrgRoute =
  ThoughtsReLevelingAnEngineeringOrgRouteImport.update({
    id: '/thoughts/re-leveling-an-engineering-org',
    path: '/thoughts/re-leveling-an-engineering-org',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/thoughts/re-leveling-an-engineering-org': typeof ThoughtsReLevelingAnEngineeringOrgRoute
  '/thoughts': typeof ThoughtsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/thoughts/re-leveling-an-engineering-org': typeof ThoughtsReLevelingAnEngineeringOrgRoute
  '/thoughts': typeof ThoughtsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/thoughts/re-leveling-an-engineering-org': typeof ThoughtsReLevelingAnEngineeringOrgRoute
  '/thoughts/': typeof ThoughtsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/thoughts/re-leveling-an-engineering-org' | '/thoughts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/thoughts/re-leveling-an-engineering-org' | '/thoughts'
  id:
    | '__root__'
    | '/'
    | '/thoughts/re-leveling-an-engineering-org'
    | '/thoughts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThoughtsReLevelingAnEngineeringOrgRoute: typeof ThoughtsReLevelingAnEngineeringOrgRoute
  ThoughtsIndexRoute: typeof ThoughtsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thoughts/': {
      id: '/thoughts/'
      path: '/thoughts'
      fullPath: '/thoughts'
      preLoaderRoute: typeof ThoughtsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thoughts/re-leveling-an-engineering-org': {
      id: '/thoughts/re-leveling-an-engineering-org'
      path: '/thoughts/re-leveling-an-engineering-org'
      fullPath: '/thoughts/re-leveling-an-engineering-org'
      preLoaderRoute: typeof ThoughtsReLevelingAnEngineeringOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThoughtsReLevelingAnEngineeringOrgRoute:
    ThoughtsReLevelingAnEngineeringOrgRoute,
  ThoughtsIndexRoute: ThoughtsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
