/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as ThoughtsIndexImport } from "./routes/thoughts/index";
import { Route as ThoughtsImplementingAnArchitectureReviewImport } from "./routes/thoughts/implementing-an-architecture-review";

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const ThoughtsIndexRoute = ThoughtsIndexImport.update({
  id: "/thoughts/",
  path: "/thoughts/",
  getParentRoute: () => rootRoute,
} as any);

const ThoughtsImplementingAnArchitectureReviewRoute =
  ThoughtsImplementingAnArchitectureReviewImport.update({
    id: "/thoughts/implementing-an-architecture-review",
    path: "/thoughts/implementing-an-architecture-review",
    getParentRoute: () => rootRoute,
  } as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/thoughts/implementing-an-architecture-review": {
      id: "/thoughts/implementing-an-architecture-review";
      path: "/thoughts/implementing-an-architecture-review";
      fullPath: "/thoughts/implementing-an-architecture-review";
      preLoaderRoute: typeof ThoughtsImplementingAnArchitectureReviewImport;
      parentRoute: typeof rootRoute;
    };
    "/thoughts/": {
      id: "/thoughts/";
      path: "/thoughts";
      fullPath: "/thoughts";
      preLoaderRoute: typeof ThoughtsIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/thoughts/implementing-an-architecture-review": typeof ThoughtsImplementingAnArchitectureReviewRoute;
  "/thoughts": typeof ThoughtsIndexRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/thoughts/implementing-an-architecture-review": typeof ThoughtsImplementingAnArchitectureReviewRoute;
  "/thoughts": typeof ThoughtsIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/thoughts/implementing-an-architecture-review": typeof ThoughtsImplementingAnArchitectureReviewRoute;
  "/thoughts/": typeof ThoughtsIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/thoughts/implementing-an-architecture-review"
    | "/thoughts";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/thoughts/implementing-an-architecture-review" | "/thoughts";
  id:
    | "__root__"
    | "/"
    | "/thoughts/implementing-an-architecture-review"
    | "/thoughts/";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ThoughtsImplementingAnArchitectureReviewRoute: typeof ThoughtsImplementingAnArchitectureReviewRoute;
  ThoughtsIndexRoute: typeof ThoughtsIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThoughtsImplementingAnArchitectureReviewRoute:
    ThoughtsImplementingAnArchitectureReviewRoute,
  ThoughtsIndexRoute: ThoughtsIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/thoughts/implementing-an-architecture-review",
        "/thoughts/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/thoughts/implementing-an-architecture-review": {
      "filePath": "thoughts/implementing-an-architecture-review.tsx"
    },
    "/thoughts/": {
      "filePath": "thoughts/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
