name: Dependabot Auto Merge
on:
    pull_request:
        branches:
            - 'dependabot/**'
    workflow_dispatch:
        inputs:
            pr-number:
                required: true

jobs:
    build-and-test:
        uses: ./.github/workflows/deploy.yml
        secrets: inherit

    auto-merge:
        runs-on: ubuntu-latest
        needs: build-and-test
        permissions:
            pull-requests: write
            contents: write
        steps:
            - uses: fastify/github-action-merge-dependabot@v3
              with:
                  target: minor, patch
                  pr-number: ${{ github.event.inputs.pr-number }}
